### ISSUE TITLE
JAX 0.3.7, chex 0.1.2 problem: module 'jaxlib.xla_extension' has no attribute 'CpuDevice'

### ISSUE THREAD

**Issue by andreaskoepf** [deepmind/optax#335]
Importing optax in a fresh jax 0.3.7 installation fails due to the following issue in chex: https://github.com/deepmind/chex/issues/156
Although it is a chex issue I am reporting it here since optax depends on chex and someone else also might see it while importing optax. 

```
>>> import jax
>>> jax.__version__
'0.3.7'
>>> import optax
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/optax/__init__.py", line 17, in <module>
    from optax import experimental
  File "/usr/local/lib/python3.8/dist-packages/optax/experimental/__init__.py", line 20, in <module>
    from optax._src.experimental.complex_valued import split_real_and_imaginary
  File "/usr/local/lib/python3.8/dist-packages/optax/_src/experimental/complex_valued.py", line 32, in <module>
    import chex
  File "/usr/local/lib/python3.8/dist-packages/chex/__init__.py", line 17, in <module>
    from chex._src.asserts import assert_axis_dimension
  File "/usr/local/lib/python3.8/dist-packages/chex/_src/asserts.py", line 26, in <module>
    from chex._src import asserts_internal as _ai
  File "/usr/local/lib/python3.8/dist-packages/chex/_src/asserts_internal.py", line 32, in <module>
    from chex._src import pytypes
  File "/usr/local/lib/python3.8/dist-packages/chex/_src/pytypes.py", line 40, in <module>
    CpuDevice = jax.lib.xla_extension.CpuDevice
AttributeError: module 'jaxlib.xla_extension' has no attribute 'CpuDevice'
```

Until a new chex release is available a temporary workaround is to reinstall chex via git, e.g. `pip3 uninstall chex -y && pip3 install git+https://github.com/deepmind/chex.git` ...

**Comment by hbq1** [comment]
It was fixed in [chex v0.1.3](https://github.com/deepmind/chex/releases/tag/v0.1.3)
